# Generated by Django 4.1.7 on 2023-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveSmallIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('re_enterpassword', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('user', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
