# Generated by Django 4.1.7 on 2023-03-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_account_name_user_cpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kid', 'kid')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_stock', models.PositiveSmallIntegerField()),
                ('product_desc', models.TextField()),
                ('product_expire_date', models.PositiveSmallIntegerField()),
                ('product_image', models.ImageField(upload_to='product_pic/')),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
