# Generated by Django 4.1.7 on 2023-03-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='add',
            new_name='user',
        ),
    ]
