# Generated by Django 4.1.7 on 2023-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_add_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_expire_date',
            field=models.CharField(max_length=100),
        ),
    ]
